#' Calculate Indirectly Standardised ratio for deprivation quintiles, standardised by age and/or sex
#'
#' This function uses negative binomial regression, to counter overdispersion, to adjust data by calculating and expected rate of events, which is compared to the observed event: observed / expected.
#' A ratio of 1 means observed = expected, <1 means observed < expected, and >1 means observed > expected.
#'
#' @param .dt A data.frame contain data you need to calculate the table with the following column names:
#' * numerator - the count of events in question
#' * denominator - the population or group at risk, or group/segment
#' * imd_code - numeric encoded IMD quintile, with unknown coded as 999
#' * age_group_code - age bands used for standardisation.  Bin/age band size is not important provided it is consistent.
#' * sex_group_code - numeric encoded sex
#' @param age TRUE/FALSE whether to include age in the standardisation.
#' @param sex TRUE/FALSE whether to include sex in the standardisation.
#'
#' @returns a data.frame with
#' @export
#'
#' @importFrom stats as.formula coef confint rbinom glm.control
#' @import MASS
#'
#' @examples
#' data(ISR_example)
#' ISR_deprivation(ISR_example)
#'
ISR_deprivation <-
  function(.dt,
           age=TRUE,
           sex=FALSE) {


    # Prepare factors
    .dt$age_group_code_f <- factor(.dt$age_group_code)
    .dt$imd_code_f <- factor(.dt$imd_code, levels = c("1","2","3","4","5","999"),
                             labels = c("1","2","3","4","5","999"))

    # Build formula dynamically using switch
    predictors <- c("imd_code_f")

    if (age) predictors <- c(predictors, "age_group_code_f")
    if (sex) predictors <- c(predictors, "sex_group_code")

    formula_str <- paste("numerator ~", paste(predictors, collapse = " + "), "+ offset(log(denominator))")
    model_formula <- as.formula(formula_str)

    # Fit negative binomial model
    model <- glm.nb(model_formula, data = .dt, control = glm.control(maxit=100))

    cis <- confint(model)

    # Extract coefficients for IMD quintiles
    out_coefs <- data.frame(
      imd_quintile = c("2","3","4","5","999"),
      ratio = exp(coef(model)[2:6]),
      lowerCI = exp(cis[2:6, 1]),
      upperCI = exp(cis[2:6, 2])
    )

    return(out_coefs)
  }



#' Plot function for output parameters of ISR calculation
#'
#' @param .dt A data.frame, generated by ISR_deprivation
#' @param description text to be included in the plot title, default example for MI admissions in 2024/25
#' @param y_scale vector of values, such as the default generated by `seq`.  Default around the 0 - 1.2 range
#'
#' @returns A ggplot object (list)
#' @import ggplot2
#'
#' @export
#'
#' @examples
#' data(ISR_example)
#' standardised_dep <- ISR_deprivation(ISR_example)
#' ISR_deprivation_plot(standardised_dep)
#'
ISR_deprivation_plot <-
  function(.dt,
           description = "Myocardial Infarction (Under 75yrs) - 2024/25",
           y_scale = seq(0,1.5,0.1)) {

    imd_quintile <- ratio <- lowerCI <- upperCI <- NULL

    ggplot(.dt, aes(x = imd_quintile, y = ratio, fill = imd_quintile)) +
      geom_col(show.legend = FALSE, alpha = 0.8) +
      geom_errorbar(aes(ymin = lowerCI, ymax = upperCI, width = 0.5)) +
      geom_hline(yintercept = 1, linetype = "dashed", col = "red", linewidth = 1) +
      scale_fill_brewer(palette = "Dark2") +
      scale_y_continuous(breaks = y_scale) +
      labs(#colour = "Deprivation Quintile",
           x = "IMD Quintile (999 = 'Unknown')",
           y = "Indirectly Standardised Ratio",
           title = paste("Age-standardised Admission Ratio Ratios:", description) ,
           subtitle = "A ratio of 1 means the rate = the rate in Quintile 1") +
      theme_minimal() +
      theme(plot.subtitle = element_text(face = "italic")
      )

  }


#' ISR example dataset
#'
#' An artificial dataset with 6 age bads, 2 sex bands and 5 IMD quintiles plus
#'  and unknown coded as 999.
#' This is here to test and demonstrate the function
#'
#' @format ## `ISR example dataset`
#' A data frame with 192 rows and 5 columns:
#' \describe{
#'   \item{age_group_code}{Numerically coded age-bands}
#'   \item{sex_group_code}{Numerically coded sex groups}
#'   \item{imd_code}{Index of multiple deprivation qunitiles, 1-5, 999 = unknown}
#'   \item{numerator}{Numerator of a given indicator}
#'   \item{denominator}{Denominator of a given indicator}
#'   ...
#' }
#' @source Constructed from code <https://github.com/Birmingham-and-Solihull-ICS/BSOLutils/blob/main/dev/build_example_data.R>
"ISR_example"

